import { Hotel, AffiliatedEntity, Booking, UserProfile } from '@/types/database';

export const FEDETUR_INFO = {
  name: 'Federación de Cooperativas y Mutuales de la Red Federal de Turismo Coop. Ltda.',
  shortName: 'FEDETUR',
  inaesMatricula: '25450',
  slogan: 'Viajar, en busca de uno mismo',
  subSlogan: 'Impulsando el desarrollo territorial a través del Turismo Social y Solidario en toda Argentina',
  legalAddress: 'Ciudad Autónoma de Buenos Aires, Argentina',
  email: 'info@fedetur.ar',
  instagram: 'https://www.instagram.com/fedeturargentina25450/?hl=es',
  youtube: 'https://youtube.com/@fedeturargentina?si=1xYOzq8-QOIePX1i',
  stats: {
    cooperativas: '+20.000',
    mutuales: '+10.000',
    asociados: '+30.000.000',
    cobertura: '90% del país',
    pbiContribution: '~10%',
  },
};

export const AFFILIATED_ENTITIES: AffiliatedEntity[] = [
  {
    id: 'ent-1',
    name: 'Mutual Personal SAMEEP (Mu.Pe.Sa)',
    acronym: 'Mu.Pe.Sa CHACO',
    entity_type: 'mutual',
    inaes_matricula: 'MAT-10293',
    province: 'Chaco',
    region: 'NEA',
    contact_email: 'mupesa@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/SAMMEP.webp',
    status: 'active',
  },
  {
    id: 'ent-2',
    name: 'Mutual Capital',
    acronym: 'Mutual Capital',
    entity_type: 'mutual',
    inaes_matricula: 'MAT-11234',
    province: 'Santiago del Estero',
    region: 'NOA',
    contact_email: 'capital@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/MutualCAPITAL-(8440).webp',
    status: 'active',
  },
  {
    id: 'ent-3',
    name: 'Cooperativa Fe.co.vi.ma.',
    acronym: 'FECOVIMA',
    entity_type: 'cooperativa',
    inaes_matricula: 'MAT-12498',
    province: 'Buenos Aires',
    region: 'Buenos Aires',
    contact_email: 'fecovima@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/FECOVIMA.webp',
    status: 'active',
  },
  {
    id: 'ent-4',
    name: 'Mutual 1° de Abril',
    acronym: '1° de Abril',
    entity_type: 'mutual',
    inaes_matricula: 'MAT-13490',
    province: 'Santiago del Estero',
    region: 'NOA',
    contact_email: 'primeroabril@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/1deAbrilSdelE.webp',
    status: 'active',
  },
  {
    id: 'ent-5',
    name: 'Asociación Mutual DECAM',
    acronym: 'DECAM',
    entity_type: 'mutual',
    inaes_matricula: 'MAT-14981',
    province: 'Buenos Aires',
    region: 'Buenos Aires',
    contact_email: 'decam@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/LogoDECAM2025.webp',
    status: 'active',
  },
  {
    id: 'ent-6',
    name: 'Mutualidad Fondo Compensador FOCOMEJ',
    acronym: 'FOCOMEJ',
    entity_type: 'mutual',
    inaes_matricula: 'MAT-15022',
    province: 'CABA',
    region: 'Buenos Aires',
    contact_email: 'focomej@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/FOCOMEJ2.webp',
    status: 'active',
  },
  {
    id: 'ent-7',
    name: 'Federación de Mutuales de La Rioja',
    acronym: 'Fed. Riojanas',
    entity_type: 'federacion',
    inaes_matricula: 'MAT-16291',
    province: 'La Rioja',
    region: 'NOA',
    contact_email: 'larioja@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/FedMutRiojanas.webp',
    status: 'active',
  },
  {
    id: 'ent-8',
    name: 'Federación de Mutuales de Vivienda (FEMMEVI)',
    acronym: 'FEMMEVI Mendoza',
    entity_type: 'federacion',
    inaes_matricula: 'MAT-17822',
    province: 'Mendoza',
    region: 'Cuyo',
    contact_email: 'femmevi@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/FEMMEVI.webp',
    status: 'active',
  },
  {
    id: 'ent-9',
    name: 'Mutual del Gas y Petróleo',
    acronym: 'Gas y Petróleo',
    entity_type: 'mutual',
    inaes_matricula: 'MAT-18933',
    province: 'Santa Cruz',
    region: 'Patagonia',
    contact_email: 'petroleo@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/MutualGasyPetr.webp',
    status: 'active',
  },
  {
    id: 'ent-10',
    name: 'Federación de Mutuales de Ahorro y Crédito Santa Fe',
    acronym: 'Fed. Mutual Santa Fe',
    entity_type: 'federacion',
    inaes_matricula: 'MAT-19401',
    province: 'Santa Fe',
    region: 'Centro',
    contact_email: 'santafe@fedetur.ar',
    logo_url: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/FedMutAhorroStaFe.webp',
    status: 'active',
  },
];

export const REGIONAL_DATA = [
  {
    name: 'NEA',
    provinces: 'Misiones, Formosa, Chaco, Corrientes',
    coops: '1.800 cooperativas',
    mutuales: '900 mutuales',
    members: '+2.200.000 personas asociadas',
    coordinator: 'ROBERTO LISKA – Presidente de FEDETUR',
    description: 'Mayor potencial turístico natural: Cataratas del Iguazú, Esteros del Iberá y circuitos sustentables.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/NEARegion.webp',
    coverImg: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'NOA',
    provinces: 'Salta, Jujuy, Tucumán, Catamarca, La Rioja, Santiago del Estero',
    coops: '2.300 cooperativas',
    mutuales: '1.200 mutuales',
    members: '+2.800.000 personas asociadas',
    coordinator: 'BRUNO DÍAZ – Vicepresidente de FEDETUR',
    description: 'Paisajes andinos, quebradas, tradición folclórica, gastronomía y turismo comunitario.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/500px-RegionNoroeste1.webp',
    coverImg: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Centro',
    provinces: 'Córdoba, Santa Fe, Entre Ríos',
    coops: '4.000 cooperativas',
    mutuales: '2.000 mutuales',
    members: '+5.000.000 personas asociadas',
    coordinator: 'ANDRÉS SELLIEZ – Fed. Mutual de Crédito Santa Fe',
    description: 'Sierras cordobesas, termas del Litoral, turismo rural, ecoturismo y lagos.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/ReginCentrodeArgentina.webp',
    coverImg: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Cuyo',
    provinces: 'Mendoza, San Juan, San Luis',
    coops: '1.500 cooperativas',
    mutuales: '700 mutuales',
    members: '+1.800.000 personas asociadas',
    coordinator: 'ISIDRO SILVA – Fed. Mendoza',
    description: 'Rutas del vino, alta montaña, turismo aventura y termalismo al pie de la Cordillera de los Andes.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/CuyoprovinceinArgentina.webp',
    coverImg: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Buenos Aires',
    provinces: 'Provincia de Buenos Aires y CABA',
    coops: '6.000 cooperativas',
    mutuales: '3.000 mutuales',
    members: '+8.000.000 personas asociadas',
    coordinator: 'CHRISTIAN R. PEREZ BERMEGUI – Mutual DECAM',
    description: 'Costa Atlántica, sierras de Tandil y Ventana, Delta del Tigre y el mayor polo cultural del país.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/BuenosAiresProvinceinArgentinaFalklandhatched-2.webp',
    coverImg: 'https://images.unsplash.com/photo-1617854818583-09e7f077a156?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Patagonia',
    provinces: 'La Pampa, Río Negro, Neuquén, Chubut, Santa Cruz, Tierra del Fuego',
    coops: '2.500 cooperativas',
    mutuales: '1.200 mutuales',
    members: '+3.200.000 personas asociadas',
    coordinator: 'CARLOS CABO – Federación Santa Cruz',
    description: 'Glaciares, lagos patagónicos, centros de esquí, avistaje de fauna marina y fin del mundo.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Patagonia1.webp',
    coverImg: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Malvinas',
    provinces: 'Subdelegación Islas Malvinas (Tierra del Fuego)',
    coops: 'Articulación Federal',
    mutuales: 'Soberanía y Memoria',
    members: 'Representación Nacional',
    coordinator: 'ALEJANDRO SOSA – Mutual Trabajadores Petroleros TDF',
    description: 'Espacio de soberanía, hermandad y articulación federal con la red de turismo social.',
    mapImg: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Patagonia1.webp',
    coverImg: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
  },
];

export const AUTHORITIES = [
  {
    name: 'ROBERTO LISKA',
    role: 'Presidente',
    entity: 'Mutual Personal SAMEEP - MU.PE.SA. (Chaco)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Roberto-Liska-copia.webp',
  },
  {
    name: 'BRUNO DÍAZ',
    role: 'Vice-Presidente',
    entity: 'Mutual CAPITAL (Santiago del Estero)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/BrunoDaz2.webp',
  },
  {
    name: 'RODOLFO TOLOSA',
    role: 'Secretario',
    entity: 'Cooperativa FE.CO.VI.MA (Buenos Aires)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Rodolfo-Tolosa.webp',
  },
  {
    name: 'MARIANO CHEJOLÁN',
    role: 'Pro-Secretario',
    entity: 'Mutual 1ro de ABRIL (Santiago del Estero)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Mariano.webp',
  },
  {
    name: 'CHRISTIAN RODRIGO PEREZ BERMEGUI',
    role: 'Tesorero',
    entity: 'Asociación Mutual DECAM (Buenos Aires)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/WhatsAppImage2025-10-29at17.webp',
  },
  {
    name: 'IRMA PAREJAS',
    role: 'Pro-tesorera',
    entity: 'Mutualidad Fondo Compensador FOCOMEJ (CABA)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/IrmaParejas.webp',
  },
  {
    name: 'MARÍA MABEL PAZ',
    role: 'Vocal Titular',
    entity: 'Federación de Mutuales (La Rioja)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/MabelPaz.webp',
  },
  {
    name: 'ISIDRO SILVA',
    role: 'Vocal Titular',
    entity: 'Federación Mutuales de Vivienda (Mendoza)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Isidro.webp',
  },
  {
    name: 'CARLOS CABO',
    role: 'Vocal Titular',
    entity: 'Mutual de Gas y Petróleo (Santa Cruz)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/CarlosCabo.webp',
  },
  {
    name: 'ANDRÉS SELLIEZ',
    role: 'Vocal Titular',
    entity: 'Federación Mutuales Ahorro y Crédito (Santa Fe)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/AndresSelliez.webp',
  },
  {
    name: 'GUSTAVO CORVALÁN',
    role: 'Secretario de Turismo',
    entity: 'Asociación Mutual DECAM (Buenos Aires)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Gus1.webp',
  },
  {
    name: 'ADALBERTO LIZAUR',
    role: 'Síndico Suplente',
    entity: 'Asociación Mutual DECAM (Buenos Aires)',
    image: 'https://ss-cnt-001c.esmsv.com/r/content/host2/3696a6317d859ead6647480b66afbb18//editor/Adal.webp',
  },
];

export const INITIAL_HOTELS: Hotel[] = [
  {
    id: 'hotel-1',
    name: 'Hotel Mutual Selva de Iguazú & Spa',
    slug: 'hotel-selva-iguazu',
    tagline: 'Experiencia inmersiva en la selva misionera junto a las Cataratas',
    description: 'Ubicado a minutos del Parque Nacional Iguazú, nuestro complejo mutual ofrece confort inigualable, gastronomía regional, piscinas tropicales y excursiones guiadas con beneficios exclusivos para afiliados de toda la República Argentina.',
    region: 'NEA',
    province: 'Misiones',
    city: 'Puerto Iguazú',
    address: 'Av. Las Orquídeas 450, Selva Iryapú',
    contact_email: 'reservas.iguazu@fedetur.ar',
    contact_phone: '+54 3757 421098',
    whatsapp: '+5493757421098',
    star_rating: 4,
    check_in_time: '14:00',
    check_out_time: '10:00',
    status: 'approved',
    featured: true,
    amenities: ['wifi', 'pool', 'breakfast', 'ac', 'restaurant', 'parking', 'spa'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: new Date().toISOString(),
    room_types: [
      {
        id: 'room-1-1',
        hotel_id: 'hotel-1',
        name: 'Habitación Doble Superior Selva',
        description: 'Amplia habitación con balcón privado hacia el dosel de la selva, cama King Size, smart TV y frigobar.',
        capacity_adults: 2,
        capacity_children: 1,
        bed_configuration: '1 Cama King o 2 Camas Twin',
        base_price_night: 85000,
        fedetur_discount_percentage: 25,
        total_inventory: 12,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Aire Acondicionado', 'Balcón con vista', 'Smart TV 50"', 'Desayuno Buffet incluido', 'Caja fuerte'],
      },
      {
        id: 'room-1-2',
        hotel_id: 'hotel-1',
        name: 'Suite Familiar Aventura',
        description: 'Dos ambientes comunicados ideales para grupos familiares. Capacidad hasta 4 personas con dos baños completos.',
        capacity_adults: 4,
        capacity_children: 2,
        bed_configuration: '1 Cama Queen + 2 Camas Twin',
        base_price_night: 135000,
        fedetur_discount_percentage: 30,
        total_inventory: 6,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Dos baños completos', 'Frigobar', 'Microondas', 'Desayuno familiar', 'Hidromasaje'],
      },
    ],
  },
  {
    id: 'hotel-2',
    name: 'Hostería Solidaria Nahuel Huapi',
    slug: 'hosteria-nahuel-huapi',
    tagline: 'Vista panorámica al lago y a las cumbres cordilleranas de Bariloche',
    description: 'Punto de encuentro del mutualismo patagónico. Arquitectura alpina en madera y piedra, hogar a leña encendido todo el invierno, cava de vinos artesanales y acceso directo a playas lacustres.',
    region: 'Patagonia',
    province: 'Río Negro',
    city: 'San Carlos de Bariloche',
    address: 'Av. Bustillo Km 8.500',
    contact_email: 'bariloche@fedetur.ar',
    contact_phone: '+54 294 4467812',
    whatsapp: '+5492944467812',
    star_rating: 4,
    check_in_time: '15:00',
    check_out_time: '11:00',
    status: 'approved',
    featured: true,
    amenities: ['wifi', 'breakfast', 'restaurant', 'parking', 'heating', 'lake_view'],
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: new Date().toISOString(),
    room_types: [
      {
        id: 'room-2-1',
        hotel_id: 'hotel-2',
        name: 'Cabaña Alpina Vista Lago',
        description: 'Cálida cabaña con piso de madera nativa, ventanal de piso a techo hacia el Nahuel Huapi y calefacción central.',
        capacity_adults: 2,
        capacity_children: 1,
        bed_configuration: '1 Cama King Size',
        base_price_night: 92000,
        fedetur_discount_percentage: 20,
        total_inventory: 8,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Vista al Lago', 'Hogar a leña', 'Desayuno Patagónico', 'WiFi Alta Velocidad'],
      },
    ],
  },
  {
    id: 'hotel-3',
    name: 'Gran Hotel Cooperativo Mendoza & Viñedos',
    slug: 'hotel-cooperativo-mendoza',
    tagline: 'Confort urbano y enoturismo en el corazón de la capital cuyana',
    description: 'Estratégicamente ubicado a 3 cuadras de la Plaza Independencia. Cuenta con piscina en la terraza, microcine cooperativo, estacionamiento cubierto y convenios con bodegas de Maipú y Luján de Cuyo.',
    region: 'Cuyo',
    province: 'Mendoza',
    city: 'Mendoza Capital',
    address: 'Calle San Martín 1140',
    contact_email: 'mendoza@fedetur.ar',
    contact_phone: '+54 261 4293044',
    whatsapp: '+5492614293044',
    star_rating: 4,
    check_in_time: '14:00',
    check_out_time: '10:00',
    status: 'approved',
    featured: true,
    amenities: ['wifi', 'pool', 'breakfast', 'ac', 'parking', 'gym'],
    images: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568495248636-6432b97bd949?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: new Date().toISOString(),
    room_types: [
      {
        id: 'room-3-1',
        hotel_id: 'hotel-3',
        name: 'Habitación Clásica Cuyana',
        description: 'Habitación moderna con aire acondicionado frío/calor, escritorio de trabajo y baño con hidromasaje.',
        capacity_adults: 2,
        capacity_children: 0,
        bed_configuration: '1 Cama Matrimonial',
        base_price_night: 70000,
        fedetur_discount_percentage: 25,
        total_inventory: 15,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Desayuno buffet', 'Piscina en terraza', 'Acceso al Gimnasio', 'Estacionamiento'],
      },
    ],
  },
  {
    id: 'hotel-4',
    name: 'Resort Mutualista Serranías de Carlos Paz',
    slug: 'resort-carlos-paz',
    tagline: 'El epicentro del descanso familiar en el Valle de Punilla',
    description: 'Parque arbolado de 3 hectáreas con canchas de fútbol, tenis y pádel, 3 piscinas climatizadas, animación infantil y régimen de media pensión para mutualistas.',
    region: 'Centro',
    province: 'Córdoba',
    city: 'Villa Carlos Paz',
    address: 'Av. San Martín 2450',
    contact_email: 'carlospaz@fedetur.ar',
    contact_phone: '+54 3541 430911',
    whatsapp: '+5493541430911',
    star_rating: 3,
    check_in_time: '13:00',
    check_out_time: '10:00',
    status: 'approved',
    featured: true,
    amenities: ['wifi', 'pool', 'breakfast', 'restaurant', 'parking', 'games_room'],
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: new Date().toISOString(),
    room_types: [
      {
        id: 'room-4-1',
        hotel_id: 'hotel-4',
        name: 'Departamento Familiar Serranía',
        description: 'Departamento equipado con cocina, vajilla, sala de estar y dos dormitorios.',
        capacity_adults: 4,
        capacity_children: 2,
        bed_configuration: '1 Cama Matrimonial + 3 Camas Simples',
        base_price_night: 95000,
        fedetur_discount_percentage: 20,
        total_inventory: 10,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Cocina completa', 'Parrilla individual', 'Piscinas climatizadas', 'Canchas deportivas'],
      },
    ],
  },
  {
    id: 'hotel-5',
    name: 'Hotel Fedetur Costa Azul Mar del Plata',
    slug: 'hotel-costa-azul-mdq',
    tagline: 'Frente a las mejores playas de La Perla para el verano de la familia mutualista',
    description: 'A 50 metros del mar. Salón comedor con vista abierta al océano Atlántico, carpas en balneario concertado y desayuno continental incluido.',
    region: 'Buenos Aires',
    province: 'Buenos Aires',
    city: 'Mar del Plata',
    address: 'Boulevard Marítimo Patricio Peralta Ramos 1820',
    contact_email: 'mardelplata@fedetur.ar',
    contact_phone: '+54 223 4951122',
    whatsapp: '+5492234951122',
    star_rating: 3,
    check_in_time: '14:00',
    check_out_time: '10:00',
    status: 'approved',
    featured: true,
    amenities: ['wifi', 'breakfast', 'restaurant', 'sea_view', 'parking'],
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: new Date().toISOString(),
    room_types: [
      {
        id: 'room-5-1',
        hotel_id: 'hotel-5',
        name: 'Habitación Doble Frente al Mar',
        description: 'Balcón privado con vista directa al mar, ventilador de techo, TV por cable y sommier nuevo.',
        capacity_adults: 2,
        capacity_children: 1,
        bed_configuration: '1 Cama Queen Size',
        base_price_night: 68000,
        fedetur_discount_percentage: 22,
        total_inventory: 20,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Vista panorámica al mar', 'Desayuno Buffet', 'Convenio carpa balneario', 'Recepción 24hs'],
      },
    ],
  },
  {
    id: 'hotel-6',
    name: 'Posada Colonial Valles Calchaquíes',
    slug: 'posada-valle-calchaqui',
    tagline: 'Cultura ancestral, serenidad y cielo estrellado en el norte argentino',
    description: 'En Cafayate, entre viñedos de torrontés y formaciones rojizas. Galerías coloniales de adobe, piscina solarium y cocina de hornos de barro.',
    region: 'NOA',
    province: 'Salta',
    city: 'Cafayate',
    address: 'Ruta 40 Km 4340',
    contact_email: 'salta@fedetur.ar',
    contact_phone: '+54 3868 421900',
    whatsapp: '+5493868421900',
    star_rating: 4,
    check_in_time: '14:00',
    check_out_time: '11:00',
    status: 'approved',
    featured: true,
    amenities: ['wifi', 'pool', 'breakfast', 'restaurant', 'parking'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: new Date().toISOString(),
    room_types: [
      {
        id: 'room-6-1',
        hotel_id: 'hotel-6',
        name: 'Suite Colonial Quebrada',
        description: 'Espaciosa suite con techos de caña y algarrobo, chimenea y terraza hacia los viñedos.',
        capacity_adults: 2,
        capacity_children: 0,
        bed_configuration: '1 Cama King Size',
        base_price_night: 78000,
        fedetur_discount_percentage: 25,
        total_inventory: 8,
        is_active: true,
        images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80'],
        amenities: ['Degustación de vinos de cortesía', 'Desayuno artesanal', 'Solarium', 'Estacionamiento cerrado'],
      },
    ],
  },
];

export const MOCK_USER_PROFILE: UserProfile = {
  id: 'user-demo-1',
  email: 'asociado@mupesa.org.ar',
  full_name: 'Alberto Ezequiel García',
  dni_cuit: '20-38492019-4',
  phone: '+54 9 11 5829-4401',
  role: 'afiliado',
  entity_id: 'ent-1',
  entity_name: 'Mutual Personal SAMEEP (Mu.Pe.Sa CHACO)',
  is_verified: true,
  created_at: '2025-01-15T10:00:00Z',
};

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    booking_code: 'FDT-2026-8941',
    affiliate_id: 'user-demo-1',
    affiliate_name: 'Alberto Ezequiel García',
    affiliate_dni: '38.492.019',
    hotel_id: 'hotel-1',
    hotel_name: 'Hotel Mutual Selva de Iguazú & Spa',
    hotel_city: 'Puerto Iguazú, Misiones (NEA)',
    hotel_image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
    room_type_id: 'room-1-1',
    room_name: 'Habitación Doble Superior Selva',
    check_in_date: '2026-09-15',
    check_out_date: '2026-09-20',
    nights_count: 5,
    guests_count: 2,
    guest_details: [
      { full_name: 'Alberto Ezequiel García', dni: '38.492.019', is_primary: true },
      { full_name: 'María Laura Gómez', dni: '39.102.394', is_primary: false },
    ],
    price_per_night: 63750, // Con 25% desc aplicado
    subtotal: 425000,
    discount_amount: 106250,
    total_amount: 318750,
    status: 'confirmed',
    payment_id: 'MP-893049102',
    payment_status: 'approved',
    special_requests: 'Habitación en piso alto cerca del mirador.',
    created_at: '2026-08-20T14:32:00Z',
  },
  {
    id: 'bk-2',
    booking_code: 'FDT-2026-9210',
    affiliate_id: 'user-demo-1',
    affiliate_name: 'Alberto Ezequiel García',
    affiliate_dni: '38.492.019',
    hotel_id: 'hotel-2',
    hotel_name: 'Hostería Solidaria Nahuel Huapi',
    hotel_city: 'San Carlos de Bariloche, Río Negro (Patagonia)',
    hotel_image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
    room_type_id: 'room-2-1',
    room_name: 'Cabaña Alpina Vista Lago',
    check_in_date: '2026-10-10',
    check_out_date: '2026-10-14',
    nights_count: 4,
    guests_count: 2,
    guest_details: [
      { full_name: 'Alberto Ezequiel García', dni: '38.492.019', is_primary: true },
    ],
    price_per_night: 73600,
    subtotal: 368000,
    discount_amount: 73600,
    total_amount: 294400,
    status: 'pending_payment',
    created_at: '2026-08-27T09:15:00Z',
  },
];
